# Generated by Django 5.0.7 on 2026-02-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll_core', '0051_payrollpolicy_vacation_bonus_days_per_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Clave interna: hikvision, zkteco, etc.', max_length=50, unique=True, verbose_name='Identificador')),
                ('display_name', models.CharField(help_text='Nombre legible: Hikvision ISAPI', max_length=100, verbose_name='Nombre para mostrar')),
                ('protocol', models.CharField(choices=[('isapi', 'Hikvision ISAPI (HTTP/REST)'), ('pull_sdk', 'ZKTeco Pull SDK'), ('push', 'Push Event (Webhook)')], max_length=20, verbose_name='Protocolo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo Biométrico',
                'verbose_name_plural': 'Tipos de Dispositivos Biométricos',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Huellero Entrada Principal', max_length=100, verbose_name='Nombre del dispositivo')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('port', models.IntegerField(default=80, verbose_name='Puerto')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Usuario del dispositivo')),
                ('password', models.CharField(help_text='Contraseña del dispositivo biométrico', max_length=255, verbose_name='Contraseña')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Número de serie')),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Versión de firmware')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('location', models.CharField(blank=True, default='', help_text='Ej: Puerta principal, Piso 2', max_length=200, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('last_event_time', models.DateTimeField(blank=True, help_text='Timestamp del último evento descargado (para sincronización incremental)', null=True, verbose_name='Último evento registrado')),
                ('status', models.CharField(choices=[('online', 'En línea'), ('offline', 'Fuera de línea'), ('error', 'Error'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='Estado')),
                ('status_detail', models.TextField(blank=True, default='', help_text='Mensaje de error o información adicional', verbose_name='Detalle del estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='biometrics.biometricdevicetype', verbose_name='Tipo de dispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo Biométrico',
                'verbose_name_plural': 'Dispositivos Biométricos',
                'ordering': ['name'],
                'unique_together': {('ip_address', 'port')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_device_id', models.CharField(help_text='Número de empleado registrado en el huellero', max_length=50, verbose_name='ID en dispositivo')),
                ('employee_name_device', models.CharField(blank=True, default='', help_text='Nombre registrado en el huellero (para referencia)', max_length=100, verbose_name='Nombre en dispositivo')),
                ('event_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('break_start', 'Inicio Descanso'), ('break_end', 'Fin Descanso'), ('unknown', 'Desconocido')], default='unknown', max_length=15, verbose_name='Tipo de evento')),
                ('verification_mode', models.CharField(choices=[('fingerprint', 'Huella Dactilar'), ('card', 'Tarjeta'), ('face', 'Reconocimiento Facial'), ('password', 'Contraseña'), ('combined', 'Combinado'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Modo de verificación')),
                ('timestamp', models.DateTimeField(help_text='Timestamp del evento en el dispositivo', verbose_name='Fecha y hora del evento')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Respuesta original del dispositivo (para debug)', verbose_name='Datos crudos')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Sincronizado el')),
                ('employee', models.ForeignKey(blank=True, help_text='Se asocia automáticamente vía EmployeeDeviceMapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='payroll_core.employee', verbose_name='Empleado')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='biometrics.biometricdevice', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Evento de Asistencia',
                'verbose_name_plural': 'Eventos de Asistencia',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='biometrics__timesta_4a0e0a_idx'), models.Index(fields=['employee', 'timestamp'], name='biometrics__employe_135e82_idx'), models.Index(fields=['employee_device_id'], name='biometrics__employe_2cd911_idx')],
                'unique_together': {('device', 'employee_device_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_employee_id', models.CharField(help_text='Número asignado al empleado en el huellero', max_length=50, verbose_name='ID del empleado en el dispositivo')),
                ('is_enrolled', models.BooleanField(default=False, help_text='¿El empleado tiene su huella capturada en este dispositivo?', verbose_name='Huella registrada')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro de huella')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='biometrics.biometricdevice', verbose_name='Dispositivo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Mapeo Empleado-Dispositivo',
                'verbose_name_plural': 'Mapeos Empleado-Dispositivo',
                'ordering': ['employee', 'device'],
                'unique_together': {('employee', 'device')},
            },
        ),
    ]
