# Generated by Django 5.0 on 2026-02-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='biometrics.biometricdevice', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='verification_mode',
            field=models.CharField(choices=[('fingerprint', 'Huella Dactilar'), ('card', 'Tarjeta'), ('face', 'Reconocimiento Facial'), ('password', 'Contraseña'), ('combined', 'Combinado'), ('web', 'Reloj Web'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Modo de verificación'),
        ),
    ]
