# Generated by Django 5.0 on 2026-02-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_alter_attendanceevent_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='verification_mode',
            field=models.CharField(choices=[('fingerprint', 'Huella Dactilar'), ('card', 'Tarjeta'), ('face', 'Reconocimiento Facial'), ('password', 'Contraseña'), ('combined', 'Combinado'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Modo de verificación'),
        ),
    ]
