# Generated by Django 5.0 on 2026-02-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_alter_attendanceevent_verification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='timezone',
            field=models.CharField(default='America/Caracas', help_text='Zona horaria del dispositivo (ej: UTC, America/Caracas)', max_length=50, verbose_name='Zona Horaria'),
        ),
    ]
