# Generated by Django 5.0 on 2026-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0004_biometricdevice_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='last_error_message',
            field=models.TextField(blank=True, help_text='Detalle técnico del último fallo de conexión o sincronización', null=True, verbose_name='Último mensaje de error'),
        ),
    ]
