# Generated by Django 5.0 on 2026-03-03 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0005_biometricdevice_last_error_message'),
        ('payroll_core', '0062_company_auto_approve_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Totales')),
                ('regular_day_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Diurnas Regulares')),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Nocturnas')),
                ('overtime_day_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Extras Diurnas')),
                ('overtime_night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas Extras Nocturnas')),
                ('sunday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas en Domingos')),
                ('sunday_count', models.PositiveSmallIntegerField(default=0, verbose_name='Domingos Trabajados')),
                ('absences', models.PositiveSmallIntegerField(default=0, verbose_name='Ausencias (sin marcaje)')),
                ('days_worked', models.PositiveSmallIntegerField(default=0, verbose_name='Días Trabajados')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('detail_json', models.JSONField(blank=True, default=list, help_text='Lista de objetos con el detalle día a día (horas, tipo, etc.)', verbose_name='Desglose Diario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='payroll_core.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='payroll_core.payrollperiod', verbose_name='Periodo de Nómina')),
            ],
            options={
                'verbose_name': 'Resumen de Asistencia por Periodo',
                'verbose_name_plural': 'Resúmenes de Asistencia por Periodo',
                'ordering': ['period', 'employee__last_name'],
                'permissions': [('approve_attendanceperiodsummary', 'Puede aprobar resúmenes de asistencia')],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
