# Generated by Django 5.0 on 2026-03-04 23:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll_core', '0062_company_auto_approve_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de factura')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('vendor_rif', models.CharField(blank=True, default='', max_length=20, verbose_name='RIF del Proveedor')),
                ('invoice_date', models.DateField(verbose_name='Fecha de factura')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('document', models.FileField(blank=True, null=True, upload_to='assets/invoices/', verbose_name='Documento adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura de Adquisición',
                'verbose_name_plural': 'Facturas de Adquisición',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del activo (auto-generado o manual)', max_length=30, unique=True, verbose_name='Código interno')),
                ('serial_number', models.CharField(blank=True, default='', help_text='Extraído por OCR o ingresado manualmente', max_length=100, verbose_name='Número de serie')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del activo')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='Código de barras / QR')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de adquisición')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de adquisición')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('useful_life_years', models.PositiveIntegerField(default=5, verbose_name='Vida útil (años)')),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor residual')),
                ('current_book_value', models.DecimalField(decimal_places=2, help_text='Se actualiza automáticamente al calcular depreciación', max_digits=14, verbose_name='Valor neto en libros')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Línea Recta'), ('DECLINING_BALANCE', 'Saldos Decrecientes'), ('UNITS_OF_PRODUCTION', 'Unidades de Producción')], default='STRAIGHT_LINE', max_length=20, verbose_name='Método de depreciación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('DISPOSED', 'Dado de Baja'), ('TRANSFERRED', 'En Tránsito')], default='ACTIVE', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='payroll_core.employee', verbose_name='Custodio / Responsable')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la auditoría')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='IN_PROGRESS', max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_expected', models.PositiveIntegerField(default=0, verbose_name='Total esperados')),
                ('total_found', models.PositiveIntegerField(default=0, verbose_name='Total encontrados')),
                ('total_missing', models.PositiveIntegerField(default=0, verbose_name='Faltantes')),
                ('total_surplus', models.PositiveIntegerField(default=0, verbose_name='Sobrantes')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('FOUND', 'Encontrado'), ('MISSING', 'Faltante'), ('SURPLUS', 'Sobrante'), ('DAMAGED', 'Dañado')], max_length=10, verbose_name='Resultado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='assets.asset', verbose_name='Activo')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetaudit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Ítem de Auditoría',
                'verbose_name_plural': 'Ítems de Auditoría',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('useful_life_years', models.PositiveIntegerField(default=5, help_text='Vida útil predeterminada para activos de esta categoría', verbose_name='Vida útil (años)')),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Línea Recta'), ('DECLINING_BALANCE', 'Saldos Decrecientes'), ('UNITS_OF_PRODUCTION', 'Unidades de Producción')], default='STRAIGHT_LINE', max_length=20, verbose_name='Método de depreciación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.assetcategory', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetinvoice', verbose_name='Factura de adquisición'),
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/photos/%Y/%m/', verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Foto principal')),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='Resultado del procesamiento OCR de esta imagen', verbose_name='Datos OCR')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assets.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Foto de Activo',
                'verbose_name_plural': 'Fotos de Activos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='payroll_core.branch', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_number', models.CharField(max_length=30, unique=True, verbose_name='Número de guía')),
                ('reason', models.CharField(default='Traslado entre establecimientos de la misma empresa', max_length=200, verbose_name='Motivo del traslado')),
                ('transport_type', models.CharField(choices=[('PRIVATE', 'Transporte Privado'), ('PUBLIC', 'Transporte Público')], default='PRIVATE', max_length=10, verbose_name='Tipo de transporte')),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=20, verbose_name='Placa del vehículo')),
                ('driver_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre del conductor')),
                ('driver_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Cédula del conductor')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_TRANSIT', 'En Tránsito'), ('RECEIVED', 'Recibido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=12, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Despachado el')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recibido el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ManyToManyField(related_name='movements', to='assets.asset', verbose_name='Activos')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_movements', to=settings.AUTH_USER_MODEL, verbose_name='Despachado por')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_movements', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='assets.warehouse', verbose_name='Almacén destino')),
                ('origin_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='assets.warehouse', verbose_name='Almacén origen')),
            ],
            options={
                'verbose_name': 'Movimiento de Activos',
                'verbose_name_plural': 'Movimientos de Activos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetaudit',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets.warehouse', verbose_name='Almacén auditado'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.warehouse', verbose_name='Almacén actual'),
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='Fecha del período')),
                ('method', models.CharField(max_length=20, verbose_name='Método aplicado')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto depreciado')),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor antes')),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor después')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset', verbose_name='Activo')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Calculado por')),
            ],
            options={
                'verbose_name': 'Depreciación',
                'verbose_name_plural': 'Depreciaciones',
                'ordering': ['-period_date'],
                'unique_together': {('asset', 'period_date')},
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='assets_asse_code_97d73a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['warehouse'], name='assets_asse_warehou_5ab6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='assets_asse_categor_7db38a_idx'),
        ),
    ]
