# Generated by Django 5.0.7 on 2026-01-31 13:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll_core', '0045_alter_payrollconcept_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Primer día de vacaciones', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Último día de vacaciones', verbose_name='Fecha de Fin')),
                ('days_requested', models.PositiveIntegerField(help_text='Cantidad de días de vacaciones solicitados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Solicitados')),
                ('return_date', models.DateField(blank=True, help_text='Fecha en que el empleado se reintegra al trabajo (calculada)', null=True, verbose_name='Fecha de Reincorporación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('PROCESSED', 'Procesada')], default='DRAFT', help_text='Estado actual de la solicitud', max_length=20, verbose_name='Estado')),
                ('vacation_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLLECTIVE', 'Colectiva')], default='INDIVIDUAL', help_text='Individual o Colectiva (cierre de empresa)', max_length=20, verbose_name='Tipo de Vacación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la solicitud', verbose_name='Observaciones')),
                ('approved_by', models.CharField(blank=True, help_text='Usuario que aprobó la solicitud', max_length=100, verbose_name='Aprobado Por')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('contract', models.ForeignKey(blank=True, help_text='Contrato vigente al momento de la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='payroll_core.laborcontract', verbose_name='Contrato Laboral')),
                ('employee', models.ForeignKey(help_text='Empleado que solicita las vacaciones', on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField(help_text='Año de servicio al que corresponde el movimiento (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Año del Período')),
                ('transaction_type', models.CharField(choices=[('ACCRUAL', 'Ganado'), ('USAGE', 'Disfrutado'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('days', models.IntegerField(help_text='Cantidad de días (positivo=ganado, negativo=consumido)', verbose_name='Días')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Movimiento')),
                ('description', models.TextField(help_text='Detalle del movimiento', verbose_name='Descripción')),
                ('created_by', models.CharField(default='SYSTEM', max_length=100, verbose_name='Creado Por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacation_balance_entries', to='payroll_core.employee', verbose_name='Empleado')),
                ('related_request', models.ForeignKey(blank=True, help_text='Solicitud de vacaciones asociada a este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_entries', to='vacations.vacationrequest', verbose_name='Solicitud Relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento de Vacaciones',
                'verbose_name_plural': 'Movimientos de Vacaciones',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['employee', '-start_date'], name='vacations_v_employe_7a9fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['status'], name='vacations_v_status_bfd02b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['start_date', 'end_date'], name='vacations_v_start_d_b1e7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationbalance',
            index=models.Index(fields=['employee', '-transaction_date'], name='vacations_v_employe_c058c9_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationbalance',
            index=models.Index(fields=['transaction_type'], name='vacations_v_transac_2dd266_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationbalance',
            index=models.Index(fields=['period_year'], name='vacations_v_period__b5d673_idx'),
        ),
    ]
