# Generated by Django 5.0.7 on 2026-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del feriado', unique=True, verbose_name='Fecha')),
                ('name', models.CharField(help_text='Nombre del feriado (ej: Día del Trabajador)', max_length=100, verbose_name='Nombre')),
                ('is_national', models.BooleanField(default=True, help_text='¿Es un feriado nacional?', verbose_name='Nacional')),
                ('is_recurring', models.BooleanField(default=True, help_text='¿Se repite cada año en la misma fecha?', verbose_name='Recurrente')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='vacations_h_date_8619d6_idx'), models.Index(fields=['is_national'], name='vacations_h_is_nati_1cf4d2_idx')],
            },
        ),
    ]
