# Generated by Django 5.0.7 on 2026-01-31 17:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_seed_holidays_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Fecha en que se procesó el pago', verbose_name='Fecha de Pago')),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Diario')),
                ('vacation_days', models.PositiveIntegerField(help_text='Días hábiles de vacaciones disfrutados', verbose_name='Días de Vacaciones')),
                ('rest_days', models.PositiveIntegerField(default=0, help_text='Sábados y Domingos dentro del período', verbose_name='Días de Descanso')),
                ('holiday_days', models.PositiveIntegerField(default=0, help_text='Feriados nacionales dentro del período', verbose_name='Días Feriados')),
                ('bonus_days', models.PositiveIntegerField(help_text='Días de bono vacacional (Art. 192 LOTTT)', verbose_name='Días de Bono')),
                ('vacation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Vacaciones')),
                ('rest_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Monto Días Descanso')),
                ('holiday_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Monto Días Feriados')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Bono Vacacional')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Bruto')),
                ('ivss_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Deducción IVSS (4%)')),
                ('faov_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Deducción FAOV (1%)')),
                ('rpe_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Deducción RPE (0.5%)')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total Deducciones')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Neto a Pagar')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='vacations/receipts/', verbose_name='Recibo PDF')),
                ('calculation_trace', models.TextField(blank=True, help_text='Registro detallado del cálculo para auditoría', verbose_name='Traza de Cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('vacation_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='vacations.vacationrequest', verbose_name='Solicitud de Vacaciones')),
            ],
            options={
                'verbose_name': 'Pago de Vacaciones',
                'verbose_name_plural': 'Pagos de Vacaciones',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
