# Generated by Django 5.0 on 2026-02-21 00:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_add_vacationpayment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationpayment',
            name='currency',
            field=models.CharField(default='VES', help_text='Moneda original del salario (USD o VES)', max_length=3, verbose_name='Moneda del Cálculo'),
        ),
        migrations.AddField(
            model_name='vacationpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tasa USD→VES usada al momento del pago', max_digits=18, verbose_name='Tasa de Cambio'),
        ),
        migrations.AddField(
            model_name='vacationpayment',
            name='gross_amount_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Bruto (VES)'),
        ),
        migrations.AddField(
            model_name='vacationpayment',
            name='net_amount_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Neto (VES)'),
        ),
        migrations.AddField(
            model_name='vacationpayment',
            name='total_deductions_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Deducciones (VES)'),
        ),
        migrations.CreateModel(
            name='VacationPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_code', models.CharField(help_text='Ej: VAC_SALARY, VAC_BONUS, DED_IVSS', max_length=20, verbose_name='Código Concepto')),
                ('concept_name', models.CharField(help_text='Descripción legible del concepto', max_length=150, verbose_name='Nombre Concepto')),
                ('kind', models.CharField(choices=[('EARNING', 'Asignación'), ('DEDUCTION', 'Deducción')], max_length=20, verbose_name='Tipo')),
                ('days', models.IntegerField(default=0, help_text='Cantidad de días aplicados (0 para deducciones)', verbose_name='Días')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario diario usado para este concepto', max_digits=18, verbose_name='Tasa Diaria')),
                ('amount_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto inmutable en Bolívares', max_digits=18, verbose_name='Monto (VES)')),
                ('amount_usd_ref', models.DecimalField(blank=True, decimal_places=2, help_text='Referencia en USD al momento del cálculo', max_digits=18, null=True, verbose_name='Monto Ref. (USD)')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje aplicado (para deducciones)', max_digits=5, verbose_name='Porcentaje')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vacations.vacationpayment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago Vacacional',
                'verbose_name_plural': 'Detalles de Pago Vacacional',
                'ordering': ['kind', 'concept_code'],
            },
        ),
    ]
