# Generated by Django 5.0 on 2026-02-25 14:31

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0058_historicalcompany_historicaldepartment_and_more'),
        ('vacations', '0005_vacationpayment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVacationRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Primer día de vacaciones', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Último día de vacaciones', verbose_name='Fecha de Fin')),
                ('days_requested', models.PositiveIntegerField(help_text='Cantidad de días de vacaciones solicitados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Solicitados')),
                ('return_date', models.DateField(blank=True, help_text='Fecha en que el empleado se reintegra al trabajo (calculada)', null=True, verbose_name='Fecha de Reincorporación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('PROCESSED', 'Procesada')], default='DRAFT', help_text='Estado actual de la solicitud', max_length=20, verbose_name='Estado')),
                ('vacation_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLLECTIVE', 'Colectiva')], default='INDIVIDUAL', help_text='Individual o Colectiva (cierre de empresa)', max_length=20, verbose_name='Tipo de Vacación')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la solicitud', verbose_name='Observaciones')),
                ('approved_by', models.CharField(blank=True, help_text='Usuario que aprobó la solicitud', max_length=100, verbose_name='Aprobado Por')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, help_text='Contrato vigente al momento de la solicitud', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll_core.laborcontract', verbose_name='Contrato Laboral')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, help_text='Empleado que solicita las vacaciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll_core.employee', verbose_name='Empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Solicitud de Vacaciones',
                'verbose_name_plural': 'historical Solicitudes de Vacaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
