# Generated by Django 5.0 on 2026-03-07 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll_core', '0062_company_auto_approve_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Apertura Diaria, Legal Mensual', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('requires_image', models.BooleanField(default=False)),
                ('tracks_expiration', models.BooleanField(default=False, help_text='¿Esta pregunta evalúa la caducidad de un permiso/documento?')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='payroll_core.branch')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='audits.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AuditAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compliant', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='audits/evidence/%Y/%m/')),
                ('is_expiry_alert_sent', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='audits.audit')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='audits.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audits.questioncategory'),
        ),
    ]
