# Generated by Django 5.0 on 2026-03-07 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('payroll_core', '0063_add_audits_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Mantenimiento, Operaciones, Legal, Inventario', max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
            },
        ),
        migrations.RemoveField(
            model_name='auditanswer',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='auditanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='template',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('VERIFIED', 'Verificado/Aprobado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, help_text='Fecha límite para completar la tarea', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, help_text='Usuario responsable (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(help_text='Sede en la que se debe ejecutar la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='payroll_core.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='audits.taskcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/evidence/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentario final del empleado al subir la evidencia')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audits.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='AuditAnswer',
        ),
        migrations.DeleteModel(
            name='ChecklistTemplate',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
