# Generated by Django 5.0 on 2026-03-07 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_taskcategory_remove_auditanswer_audit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Áreas Externas, Farmacia, Depósito', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Checklist Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Apertura Diaria, Operativo Quincenal, Legal Mensual', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskevidence',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, help_text='Ej: Ventanales, Limpieza Fachada', max_length=255)),
                ('text', models.TextField(help_text='El punto específico a evaluar')),
                ('requires_image', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audits.checklistcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='audits.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='audits.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Cumple'), ('NOK', 'No Cumple'), ('NA', 'No Aplica'), ('NE', 'No Evaluado')], default='NE', max_length=5)),
                ('comments', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasks/checklist/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='audits.task')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audits.checklistitem')),
            ],
            options={
                'unique_together': {('task', 'item')},
            },
        ),
    ]
