# Generated by Django 5.0 on 2026-03-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_checklistcategory_checklisttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='preferred_day',
            field=models.IntegerField(blank=True, help_text='Día de la semana (1-7) o día del mes (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Hora sugerida para la ejecución', null=True),
        ),
    ]
