# Generated by Django 5.0 on 2026-03-07 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_checklisttemplate_frequency_and_more'),
        ('payroll_core', '0063_add_audits_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Empleado responsable (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='payroll_core.employee'),
        ),
    ]
