# Generated by Django 5.0 on 2025-12-27 14:44

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='Nombre comercial o razón social de la farmacia', max_length=200, verbose_name='Nombre de la Empresa')),
                ('rif', models.CharField(help_text='Registro de Información Fiscal (ej: J-12345678-9)', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato: X-12345678-9 (donde X es J, V, E, G, P o C)', regex='^[JVEGPC]-\\d{8}-\\d$')], verbose_name='RIF')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paid_until', models.DateField(blank=True, help_text='Fecha de vencimiento de la suscripción', null=True, verbose_name='Pagado Hasta')),
                ('on_trial', models.BooleanField(default=True, verbose_name='En Período de Prueba')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, help_text='Dirección fiscal de la empresa', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
