# Generated by Django 5.0 on 2026-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price_per_employee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo mensual por empleado activo', max_digits=10, verbose_name='Precio por Empleado ($)'),
        ),
    ]
