# Generated by Django 5.0 on 2026-01-22 15:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_price_per_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='Código ISO de 3 letras (ej: USD, VES, EUR)', max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(default='$', max_length=5, verbose_name='Símbolo')),
                ('is_base_currency', models.BooleanField(default=False, verbose_name='Es Moneda Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InterestRateBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Tasa (%)')),
                ('source_url', models.URLField(blank=True, verbose_name='URL Fuente BCV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa')),
                ('date_valid', models.DateTimeField(verbose_name='Fecha de Validez')),
                ('source', models.CharField(choices=[('BCV', 'Banco Central de Venezuela'), ('MONITOR', 'Monitor Dólar'), ('PARALELO', 'Mercado Paralelo'), ('PROMEDIO', 'Promedio de Mercado')], default='BCV', max_length=20, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='customers.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date_valid'],
                'indexes': [models.Index(fields=['currency', '-date_valid'], name='customers_e_currenc_8b6c60_idx'), models.Index(fields=['source', '-date_valid'], name='customers_e_source_39f9d1_idx')],
                'unique_together': {('currency', 'date_valid', 'source')},
            },
        ),
    ]
