# Generated by Django 5.0 on 2025-12-27 14:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='Código ISO de 3 letras (ej: USD, VES, EUR)', max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre completo de la moneda', max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(default='$', help_text='Símbolo de la moneda (ej: $, Bs., €)', max_length=5, verbose_name='Símbolo')),
                ('is_base_currency', models.BooleanField(default=False, help_text='Indica si es la moneda principal para reportes (generalmente VES)', verbose_name='Es Moneda Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Cantidad de decimales para mostrar', verbose_name='Decimales')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Soltero(a)'), ('M', 'Casado(a)'), ('D', 'Divorciado(a)'), ('W', 'Viudo(a)'), ('C', 'Concubino(a)')], max_length=1, verbose_name='Estado Civil')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('national_id', models.CharField(help_text='Formato: V-12345678 o E-12345678', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener el formato: V-12345678 o E-12345678', regex='^[VE]-\\d{7,8}$')], verbose_name='Cédula de Identidad')),
                ('rif', models.CharField(blank=True, help_text='Registro de Información Fiscal (opcional)', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato: V-12345678-9', regex='^[JVEGPC]-\\d{8}-\\d$')], verbose_name='RIF Personal')),
                ('ivss_code', models.CharField(blank=True, help_text='Número de afiliación al Instituto Venezolano de los Seguros Sociales', max_length=20, verbose_name='Código IVSS')),
                ('faov_code', models.CharField(blank=True, help_text='Número de cuenta del Fondo de Ahorro Obligatorio para la Vivienda', max_length=20, verbose_name='Código FAOV/Banavih')),
                ('employee_code', models.CharField(blank=True, help_text='Código interno del empleado', max_length=20, null=True, unique=True, verbose_name='Código de Empleado')),
                ('hire_date', models.DateField(help_text='Fecha de inicio de la relación laboral (vital para antigüedad)', verbose_name='Fecha de Ingreso')),
                ('termination_date', models.DateField(blank=True, help_text='Fecha de terminación de la relación laboral', null=True, verbose_name='Fecha de Egreso')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el empleado está actualmente laborando', verbose_name='Activo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('bank_account_number', models.CharField(blank=True, help_text='Cuenta para depósito de nómina', max_length=30, verbose_name='Número de Cuenta')),
                ('bank_account_type', models.CharField(blank=True, help_text='Ahorro o Corriente', max_length=20, verbose_name='Tipo de Cuenta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['national_id'], name='payroll_cor_nationa_acbd19_idx'), models.Index(fields=['is_active'], name='payroll_cor_is_acti_330fa1_idx'), models.Index(fields=['hire_date'], name='payroll_cor_hire_da_6264dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Tasa de cambio a Bolívares (6 decimales para precisión)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Tasa')),
                ('date_valid', models.DateTimeField(help_text='Fecha y hora de la tasa (BCV actualiza a las 9am y 1pm)', verbose_name='Fecha de Validez')),
                ('source', models.CharField(choices=[('BCV', 'Banco Central de Venezuela'), ('MONITOR', 'Monitor Dólar'), ('PARALELO', 'Mercado Paralelo'), ('PROMEDIO', 'Promedio de Mercado')], default='BCV', help_text='Origen de la tasa de cambio', max_length=20, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales', verbose_name='Notas')),
                ('currency', models.ForeignKey(help_text='Moneda de origen para la conversión', on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='payroll_core.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date_valid'],
                'indexes': [models.Index(fields=['currency', '-date_valid'], name='payroll_cor_currenc_336e3e_idx'), models.Index(fields=['source', '-date_valid'], name='payroll_cor_source_b3dadd_idx')],
                'unique_together': {('currency', 'date_valid', 'source')},
            },
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('INDEFINITE', 'Tiempo Indeterminado'), ('FIXED_TERM', 'Tiempo Determinado'), ('PROJECT', 'Por Obra Determinada')], default='INDEFINITE', max_length=20, verbose_name='Tipo de Contrato')),
                ('salary_amount', models.DecimalField(decimal_places=2, help_text='Monto del salario en la moneda especificada', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Salario')),
                ('payment_frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual')], default='BIWEEKLY', max_length=10, verbose_name='Frecuencia de Pago')),
                ('start_date', models.DateField(help_text='Fecha de inicio del contrato', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Solo para contratos a tiempo determinado', null=True, verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este es el contrato actual del empleado', verbose_name='Vigente')),
                ('position', models.CharField(help_text='Cargo según el contrato', max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('work_schedule', models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8:00 AM - 5:00 PM', max_length=100, verbose_name='Horario de Trabajo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='payroll_core.employee', verbose_name='Empleado')),
                ('salary_currency', models.ForeignKey(help_text='Moneda en la que se pacta el salario (generalmente USD)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='payroll_core.currency', verbose_name='Moneda del Salario')),
            ],
            options={
                'verbose_name': 'Contrato Laboral',
                'verbose_name_plural': 'Contratos Laborales',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', '-start_date'], name='payroll_cor_employe_57c8ae_idx'), models.Index(fields=['is_active'], name='payroll_cor_is_acti_10ea52_idx')],
            },
        ),
    ]
