# Generated by Django 5.0 on 2025-12-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la sucursal (ej: Sucursal Centro)', max_length=100, verbose_name='Nombre de la Sede')),
                ('code', models.CharField(help_text='Código interno único para identificar la sede (ej: B001)', max_length=20, unique=True, verbose_name='Código')),
                ('address', models.TextField(blank=True, help_text='Dirección completa de la sede', verbose_name='Dirección Física')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto de la sede', max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sede está operativa', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sede a la que pertenece el empleado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll_core.branch', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sede donde se ejecuta el contrato', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='payroll_core.branch', verbose_name='Sede'),
        ),
    ]
