# Generated by Django 5.0 on 2025-12-27 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0002_branch_employee_branch_laborcontract_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: P001, IVSS, FAOV)', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Concepto')),
                ('kind', models.CharField(choices=[('EARNING', 'Asignación'), ('DEDUCTION', 'Deducción')], max_length=20, verbose_name='Tipo')),
                ('computation_method', models.CharField(choices=[('FIXED_AMOUNT', 'Monto Fijo'), ('PERCENTAGE_OF_BASIC', 'Porcentaje del Salario Base'), ('FORMULA', 'Fórmula Compleja')], default='FIXED_AMOUNT', max_length=30, verbose_name='Método de Cálculo')),
                ('value', models.DecimalField(decimal_places=4, help_text='Monto fijo O porcentaje (ej: 4.00 para 4%)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('is_salary_incidence', models.BooleanField(default=True, help_text='Indica si afecta el salario integral y prestaciones', verbose_name='Incidencia Salarial')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('currency', models.ForeignKey(help_text='Moneda del valor fijo (ignorado si es porcentaje)', on_delete=django.db.models.deletion.PROTECT, to='payroll_core.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Concepto de Nómina',
                'verbose_name_plural': 'Conceptos de Nómina',
                'ordering': ['kind', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_value', models.DecimalField(blank=True, decimal_places=4, help_text='Dejar en blanco para usar el valor global del concepto', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Personalizado')),
                ('active', models.BooleanField(default=True, help_text='Indica si este concepto se aplica al empleado', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='payroll_core.employee', verbose_name='Empleado')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll_core.payrollconcept', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Asignación de Concepto',
                'verbose_name_plural': 'Asignaciones de Conceptos',
                'ordering': ['employee', 'concept__code'],
                'unique_together': {('employee', 'concept')},
            },
        ),
    ]
