# Generated by Django 5.0 on 2025-12-28 13:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0003_payrollconcept_employeeconcept'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: 1ra Quincena Enero 2025', max_length=100, verbose_name='Nombre del Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periodo de Nómina',
                'verbose_name_plural': 'Periodos de Nómina',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_snapshot', models.JSONField(help_text='Copia de los datos del contrato (salario, cargo, etc.) al cerrar', verbose_name='Snapshot del Contrato')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Asignaciones')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Deducciones')),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Neto a Pagar')),
                ('exchange_rate_applied', models.DecimalField(decimal_places=6, help_text='Tasa BCV utilizada para este recibo', max_digits=18, verbose_name='Tasa Aplicada')),
                ('currency_code', models.CharField(help_text='Generalmente VES', max_length=3, verbose_name='Moneda del Recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll_core.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll_core.payrollperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'ordering': ['period', 'employee'],
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayslipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_code', models.CharField(max_length=20, verbose_name='Código Concepto')),
                ('concept_name', models.CharField(max_length=150, verbose_name='Nombre Concepto')),
                ('kind', models.CharField(choices=[('EARNING', 'Asignación'), ('DEDUCTION', 'Deducción')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll_core.payslip', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Detalle de Recibo',
                'verbose_name_plural': 'Detalles de Recibo',
            },
        ),
    ]
