# Generated by Django 5.0 on 2025-12-28 14:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0004_payrollperiod_payslip_payslipdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_code', models.CharField(help_text='Debe coincidir con los códigos en formulas.py (ej: H_EXTRA, B_NOCTURNO, FALTAS)', max_length=20, verbose_name='Código de Concepto')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de la novedad (horas, días o monto fijo)', max_digits=12, verbose_name='Monto/Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='payroll_core.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(limit_choices_to={'status': 'OPEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='novelties', to='payroll_core.payrollperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Novedad de Nómina',
                'verbose_name_plural': 'Novedades de Nómina',
                'ordering': ['employee', 'concept_code'],
                'unique_together': {('employee', 'period', 'concept_code')},
            },
        ),
    ]
