# Generated by Django 5.0 on 2025-12-28 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0005_payrollnovelty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='payslipdetail',
            name='amount',
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_pay_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Neto a Pagar (VES)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PAID', 'Pagado')], default='DRAFT', max_length=10, verbose_name='Estado del Recibo'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Deducciones (VES)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_income_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Ingresos (VES)'),
        ),
        migrations.AddField(
            model_name='payslipdetail',
            name='amount_src',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto Original'),
        ),
        migrations.AddField(
            model_name='payslipdetail',
            name='amount_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Monto (VES)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='currency_code',
            field=models.CharField(default='VES', help_text='Generalmente VES', max_length=3, verbose_name='Moneda del Recibo'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='exchange_rate_applied',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tasa BCV utilizada para este recibo', max_digits=18, verbose_name='Tasa Aplicada'),
        ),
    ]
