# Generated by Django 5.0 on 2025-12-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0006_remove_payslip_net_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='formula',
            field=models.TextField(blank=True, help_text='Variables disponibles: SALARIO, DIAS, LUNES, TASA, ANTIGUEDAD. Ej: (SALARIO / 30) * DIAS', null=True, verbose_name='Fórmula Python'),
        ),
        migrations.AlterField(
            model_name='payrollconcept',
            name='computation_method',
            field=models.CharField(choices=[('FIXED_AMOUNT', 'Monto Fijo'), ('PERCENTAGE_OF_BASIC', 'Porcentaje del Salario Base'), ('DYNAMIC_FORMULA', 'Fórmula Dinámica (Usuario)')], default='FIXED_AMOUNT', max_length=30, verbose_name='Método de Cálculo'),
        ),
    ]
