# Generated by Django 5.0 on 2025-12-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0007_payrollconcept_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
