# Generated by Django 5.0 on 2025-12-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0008_alter_employee_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rif', models.CharField(help_text='J-12345678-9', max_length=20, verbose_name='RIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Corporativo')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color Primario')),
                ('base_currency_symbol', models.CharField(default='Bs.', max_length=5, verbose_name='Símbolo Moneda Base')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
