# Generated by Django 5.0 on 2025-12-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0009_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='faov_code',
            field=models.CharField(blank=True, help_text='Número de cuenta del Fondo de Ahorro Obligatorio para la Vivienda', max_length=20, null=True, verbose_name='Código FAOV/Banavih'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ivss_code',
            field=models.CharField(blank=True, help_text='Número de afiliación al Instituto Venezolano de los Seguros Sociales', max_length=20, null=True, verbose_name='Código IVSS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='position',
            field=models.CharField(blank=True, help_text='Cargo según el contrato', max_length=100, null=True, verbose_name='Cargo'),
        ),
    ]
