# Generated by Django 5.0 on 2025-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0010_alter_employee_email_alter_employee_faov_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='rif',
            field=models.CharField(help_text='RIF de la sede', max_length=20, null=True, unique=True, verbose_name='RIF'),
        ),
    ]
