# Generated by Django 5.0 on 2025-12-31 18:49

import payroll_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0011_branch_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=payroll_core.models.tenant_upload_path),
        ),
    ]
