# Generated by Django 5.0.7 on 2026-01-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0013_alter_employee_department_department_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        sql="""
        -- Quitamos la restricción de obligatoriedad temporalmente
        ALTER TABLE payroll_core_employee ALTER COLUMN department DROP NOT NULL;
        
        -- Convertimos a NULL todo lo que no sea un número (ID de departamento)
        -- Esto evita el error de 'sintaxis no válida para tipo bigint'
        UPDATE payroll_core_employee 
        SET department = NULL 
        WHERE department !~ '^[0-9]+$'; 
        
        -- También los vacíos
        UPDATE payroll_core_employee SET department = NULL WHERE department = '';
        """,
        reverse_sql=migrations.RunSQL.noop
    ),
        migrations.RemoveField(
            model_name='employee',
            name='department_link',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departamento al que pertenece el empleado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll_core.department', verbose_name='Departamento'),
        ),
    ]
