# Generated by Django 5.0.7 on 2026-01-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0015_department_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborcontract',
            name='department',
        ),
    ]
