# Generated by Django 5.0.7 on 2026-01-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0016_remove_laborcontract_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborcontract',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departamento según el contrato', null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll_core.department', verbose_name='Departamento'),
        ),
    ]
