# Generated by Django 5.0.7 on 2026-01-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0017_laborcontract_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborcontract',
            name='base_salary_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sueldo Base en Bolívares (Fijo)', max_digits=10),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='includes_cestaticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Paquete Mensual en USD', max_digits=10, verbose_name='Monto del Salario'),
        ),
    ]
