# Generated by Django 5.0.7 on 2026-01-04 19:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0018_laborcontract_base_salary_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='national_minimum_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('130.00'), help_text='Base para deducciones de ley (IVSS, RPE)', max_digits=18, verbose_name='Salario Mínimo Nacional'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rif',
            field=models.CharField(blank=True, help_text='Registro de Información Fiscal (opcional)', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='El RIF debe tener el formato: V-12345678-9', regex='^[JVEGPC]-\\d{8}-\\d$')], verbose_name='RIF Personal'),
        ),
    ]
