# Generated by Django 5.0.7 on 2026-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0019_company_national_minimum_salary_alter_employee_rif'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cestaticket_journey',
            field=models.CharField(choices=[('MONTHLY', 'Mensual (Única fecha)'), ('PERIODIC', 'Proporcional en cada pago')], default='MONTHLY', max_length=10, verbose_name='Frecuencia de Cestaticket'),
        ),
        migrations.AddField(
            model_name='company',
            name='cestaticket_payment_day',
            field=models.PositiveSmallIntegerField(default=30, help_text='Si es mensual, día del mes en que se abona (ej: 30 para fin de mes)', verbose_name='Día de Pago Cestaticket'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_journey',
            field=models.CharField(choices=[('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual')], default='BIWEEKLY', max_length=10, verbose_name='Frecuencia de Nómina Principal'),
        ),
    ]
