# Generated by Django 5.0.7 on 2026-01-05 17:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0020_company_cestaticket_journey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ej: Anticipo Prestaciones, Préstamo Personal', max_length=200, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto original solicitado (Sin incluir intereses)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Principal')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ganancia o interés administrativo (0-100)', max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Monto que resta por pagar (Incluye intereses)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Pendiente')),
                ('num_installments', models.PositiveIntegerField(blank=True, help_text='Número de cuotas para pagar. Si se define, calcula la cuota automáticamente.', null=True, verbose_name='Nro. Cuotas')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto a descontar por evento de nómina', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Cuota')),
                ('frequency', models.CharField(choices=[('ALL', 'Todas las Nóminas'), ('2ND_Q', 'Solo 2da Quincena (Fin de Mes)')], default='ALL', max_length=10, verbose_name='Frecuencia de Cobro')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('ACTIVE', 'Activo'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('start_date', models.DateField(help_text='Fecha a partir de la cual se comienza a cobrar', verbose_name='Fecha Inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(help_text='Moneda del préstamo (USD o VES)', on_delete=django.db.models.deletion.PROTECT, to='payroll_core.currency', verbose_name='Moneda')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Préstamo / Anticipo',
                'verbose_name_plural': 'Préstamos y Anticipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto restado al saldo (en la moneda del préstamo)', max_digits=12, verbose_name='Monto Abonado')),
                ('payment_date', models.DateField(verbose_name='Fecha de Pago')),
                ('exchange_rate_applied', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tasa usada para convertir de VES a moneda del préstamo (si aplica)', max_digits=18, verbose_name='Tasa Cambio')),
                ('reference', models.CharField(blank=True, help_text='Ej: Nómina Quincena 1 Enero o Transferencia #1234', max_length=100, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll_core.loan', verbose_name='Préstamo')),
                ('payslip', models.ForeignKey(blank=True, help_text='Nómina donde se realizó el descuento (opcional si es abono manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='payroll_core.payslip', verbose_name='Recibo de Nómina')),
            ],
            options={
                'verbose_name': 'Abono a Préstamo',
                'verbose_name_plural': 'Abonos a Préstamos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
