# Generated by Django 5.0.7 on 2026-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0021_loan_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='show_on_payslip',
            field=models.BooleanField(default=True, help_text='Si se desactiva, este concepto se calculará (si es necesario) pero no aparecerá en el recibo del empleado.', verbose_name='Mostrar en Recibo'),
        ),
    ]
