# Generated by Django 5.0.7 on 2026-01-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0022_payrollconcept_show_on_payslip'),
    ]


def create_system_concepts(apps, schema_editor):
    PayrollConcept = apps.get_model('payroll_core', 'PayrollConcept')
    Currency = apps.get_model('payroll_core', 'Currency')
    
    # Asegurar que USD/VES existen (aunque depende de Currency migration, asumimos que ya existen o se crean)
    # Buscamos USD, si no existe, usamos el primero que aparezca o creamos dummy si hace falta.
    # En un entorno real, Currency 'USD' debería existir.
    usd_currency = Currency.objects.filter(code='USD').first()
    if not usd_currency:
        # Fallback safe: try to get any currency or creating it might fail if table empty
        # If Currency table is empty, we skip creating concepts to avoid error.
        return 

    system_concepts = [
        {
            'code': 'SUELDO_BASE',
            'name': 'Sueldo Base',
            'kind': 'EARNING',
            'computation_method': 'FIXED_AMOUNT', # Dummy, it's calculated by engine
            'value': 0,
            'is_salary_incidence': True,
            'show_on_payslip': True,
            'active': True
        },
        {
            'code': 'COMPLEMENTO',
            'name': 'Complemento Salarial',
            'kind': 'EARNING',
            'computation_method': 'FIXED_AMOUNT',
            'value': 0,
            'is_salary_incidence': False, # Complemento usually is NOT salary incidence in hybrid models
            'show_on_payslip': True, # Default visible
            'active': True
        },
        {
            'code': 'CESTATICKET',
            'name': 'Cestaticket',
            'kind': 'EARNING',
            'computation_method': 'FIXED_AMOUNT',
            'value': 0,
            'is_salary_incidence': False,
            'show_on_payslip': True,
            'active': True
        }
    ]

    for concept_data in system_concepts:
        PayrollConcept.objects.get_or_create(
            code=concept_data['code'],
            defaults={
                'name': concept_data['name'],
                'kind': concept_data['kind'],
                'computation_method': concept_data['computation_method'],
                'value': concept_data['value'],
                'currency': usd_currency,
                'is_salary_incidence': concept_data['is_salary_incidence'],
                'show_on_payslip': concept_data['show_on_payslip'],
                'active': concept_data['active']
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0022_payrollconcept_show_on_payslip'),
    ]

    operations = [
        migrations.RunPython(create_system_concepts),
    ]
