# Generated by Django 5.0 on 2026-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0023_create_system_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_base_salary',
            field=models.BooleanField(default=True, verbose_name='Mostrar Sueldo Base en Recibo'),
        ),
        migrations.AddField(
            model_name='company',
            name='show_supplement',
            field=models.BooleanField(default=True, verbose_name='Mostrar Complemento en Recibo'),
        ),
        migrations.AddField(
            model_name='company',
            name='show_tickets',
            field=models.BooleanField(default=True, verbose_name='Mostrar Cestaticket en Recibo'),
        ),
    ]
