# Generated by Django 5.0 on 2026-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0024_company_show_base_salary_company_show_supplement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='show_seniority',
            field=models.BooleanField(default=True, verbose_name='Mostrar Antigüedad en Recibo'),
        ),
    ]
