# Generated by Django 5.0 on 2026-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0025_company_show_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipdetail',
            name='tipo_recibo',
            field=models.CharField(choices=[('salario', 'Salario Base'), ('complemento', 'Complemento'), ('cestaticket', 'Cestaticket')], default='salario', max_length=20, verbose_name='Tipo de Recibo'),
        ),
    ]
