# Generated by Django 5.0 on 2026-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0026_payslipdetail_tipo_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calculation_mode',
            field=models.CharField(choices=[('STANDARD', 'Estándar (Proporcional 15/30 días)'), ('DETAILED', 'Detallado (Calendario real + Salario Promedio)')], default='STANDARD', max_length=20, verbose_name='Modo de Cálculo de Nómina'),
        ),
        migrations.AddField(
            model_name='company',
            name='rest_days_schema',
            field=models.JSONField(default=list, help_text='Lista de índices (0=Lunes, 6=Domingo). Ej: [5] para Sábados.', verbose_name='Esquema de Días de Descanso'),
        ),
    ]
