# Generated by Django 5.0 on 2026-01-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0027_company_calculation_mode_company_rest_days_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='calculation_mode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rest_days_schema',
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='appears_on_receipt',
            field=models.BooleanField(default=True, help_text='Indica si el concepto debe ser considerado para la impresión del recibo.', verbose_name='Aparece en Recibo'),
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='receipt_order',
            field=models.PositiveIntegerField(default=0, help_text='Controla la posición del concepto en el PDF (menor valor aparece primero)', verbose_name='Orden en Recibo'),
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='show_even_if_zero',
            field=models.BooleanField(default=False, help_text='Si es True, se imprimirá en el recibo incluso si el monto es 0.00', verbose_name='Mostrar aunque sea Cero'),
        ),
        migrations.AlterField(
            model_name='payrollconcept',
            name='show_on_payslip',
            field=models.BooleanField(default=True, help_text='Si se desactiva, este concepto se calculará (si es necesario) pero no aparecerá en el recibo del empleado.', verbose_name='Mostrar en Recibo (Legacy)'),
        ),
    ]
