# Generated by Django 5.0 on 2026-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0028_remove_company_calculation_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollconcept',
            options={'ordering': ['receipt_order', 'kind', 'code'], 'verbose_name': 'Concepto de Nómina', 'verbose_name_plural': 'Conceptos de Nómina'},
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Si es True, el concepto es esencial para el motor y no puede ser modificado o eliminado.', verbose_name='Concepto de Sistema'),
        ),
    ]
