# Generated by Django 5.0 on 2026-01-11 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0029_alter_payrollconcept_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cantidad/Valor Auxiliar'),
        ),
        migrations.AddField(
            model_name='payslipdetail',
            name='unit',
            field=models.CharField(default='días', max_length=20, verbose_name='Unidad'),
        ),
    ]
