# Generated by Django 5.0 on 2026-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0030_payslipdetail_quantity_payslipdetail_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipdetail',
            name='calculation_trace',
            field=models.TextField(blank=True, null=True, verbose_name='Traza de Cálculo'),
        ),
    ]
