# Generated by Django 5.0.7 on 2026-01-14 14:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0031_payslipdetail_calculation_trace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['branch', 'name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Indica si es la sede principal del tenant. Solo puede haber una.', verbose_name='Sede Principal'),
        ),
        migrations.AddField(
            model_name='company',
            name='salary_split_mode',
            field=models.CharField(choices=[('PERCENTAGE', 'Porcentaje (Base = % del Total)'), ('FIXED_BASE', 'Base Fija + Complemento Variable'), ('FIXED_BONUS', 'Complemento Fijo + Base Variable')], default='PERCENTAGE', help_text='Cómo se divide el salario total entre base y complemento', max_length=15, verbose_name='Modo de Distribución Salarial'),
        ),
        migrations.AddField(
            model_name='company',
            name='split_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Para modos FIXED_BASE o FIXED_BONUS: monto fijo en la moneda del contrato', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Fijo'),
        ),
        migrations.AddField(
            model_name='company',
            name='split_percentage_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Para modo PERCENTAGE: porcentaje del total que es sueldo base (ej: 30.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Base (%)'),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='total_salary_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, sobreescribe el sueldo base del cargo. (Monto Mensual)', max_digits=12, null=True, verbose_name='Override Sueldo Mensual'),
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del cargo (ej: Analista Senior)', max_length=100, verbose_name='Nombre del Cargo')),
                ('code', models.CharField(help_text='Código interno único del cargo (ej: ANA-SR-001)', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción de funciones y responsabilidades del cargo', verbose_name='Descripción')),
                ('default_total_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo mensual base para contratos con este cargo (en moneda seleccionada)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sueldo Total Mensual')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el cargo está disponible para nuevos contratos', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('currency', models.ForeignKey(default='USD', help_text='Moneda del sueldo base (generalmente USD)', on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='payroll_core.currency', verbose_name='Moneda')),
                ('department', models.ForeignKey(help_text='Departamento al que pertenece este cargo', on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='payroll_core.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='job_position',
            field=models.ForeignKey(blank=True, help_text='Cargo seleccionado de la estructura organizacional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='payroll_core.jobposition', verbose_name='Cargo Estructurado'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['department', 'is_active'], name='payroll_cor_departm_0c3555_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['code'], name='payroll_cor_code_5ea56f_idx'),
        ),
    ]
