# Generated by Django 5.0 on 2026-01-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0032_alter_branch_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, help_text='Cargo asociado de la estructura organizacional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll_core.jobposition', verbose_name='Cargo Estructurado'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo (Texto Legacy)'),
        ),
    ]
