# Generated by Django 5.0 on 2026-01-15 13:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0033_employee_job_position_alter_employee_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='period',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='payslip',
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='incidences',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas de incidencia (ej: ["FAOV_BASE", "ISLR_BASE"])', verbose_name='Incidencias (Tags)'),
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_payout_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Multiplicador para días feriados trabajados (ej: 1.50)', max_digits=5, verbose_name='Factor Feriados')),
                ('rest_day_payout_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Multiplicador para días de descanso trabajados', max_digits=5, verbose_name='Factor Descansos')),
                ('overtime_day_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Recargo para horas extras diurnas (ej: 1.50 = 50% recargo)', max_digits=5, verbose_name='Horas Extra Diurnas')),
                ('overtime_night_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Recargo para horas extras nocturnas', max_digits=5, verbose_name='Horas Extra Nocturnas')),
                ('night_bonus_rate', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Porcentaje de recargo por bono nocturno (ej: 0.30 = 30%)', max_digits=5, verbose_name='Bono Nocturno (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='payroll_core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Política de Nómina',
                'verbose_name_plural': 'Políticas de Nómina',
            },
        ),
        migrations.CreateModel(
            name='PayrollReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_snapshot', models.JSONField(help_text='Copia de los datos del contrato (salario, cargo, etc.) al cerrar', verbose_name='Snapshot del Contrato')),
                ('salary_base_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo base del empleado al momento del cálculo', max_digits=18, verbose_name='Salario Base Snapshot')),
                ('total_income_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Ingresos (VES)')),
                ('total_deductions_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Total Deducciones (VES)')),
                ('net_pay_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Neto a Pagar (VES)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PAID', 'Pagado')], default='DRAFT', max_length=10, verbose_name='Estado del Recibo')),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Tasa BCV utilizada para este recibo', max_digits=18, verbose_name='Tasa Snapshot')),
                ('currency_code', models.CharField(default='VES', help_text='Generalmente VES', max_length=3, verbose_name='Moneda del Recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payroll_core.employee', verbose_name='Empleado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payroll_core.payrollperiod', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Recibo de Nómina',
                'verbose_name_plural': 'Recibos de Nómina',
                'ordering': ['period', 'employee'],
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='receipt',
            field=models.ForeignKey(blank=True, help_text='Nómina donde se realizó el descuento (opcional si es abono manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='payroll_core.payrollreceipt', verbose_name='Recibo de Nómina'),
        ),
        migrations.CreateModel(
            name='PayrollReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_code', models.CharField(max_length=20, verbose_name='Código Concepto')),
                ('concept_name', models.CharField(max_length=150, verbose_name='Nombre Concepto')),
                ('kind', models.CharField(choices=[('EARNING', 'Asignación'), ('DEDUCTION', 'Deducción')], max_length=20, verbose_name='Tipo')),
                ('amount_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Monto (VES)')),
                ('tipo_recibo', models.CharField(choices=[('salario', 'Salario Base'), ('complemento', 'Complemento'), ('cestaticket', 'Cestaticket')], default='salario', max_length=20, verbose_name='Tipo de Recibo')),
                ('amount_src', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Monto Original')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cantidad/Valor Auxiliar')),
                ('unit', models.CharField(default='días', max_length=20, verbose_name='Unidad')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje Aplicado')),
                ('calculation_log', models.JSONField(blank=True, default=dict, help_text='Contiene trace, formula y variables del motor', verbose_name='Log de Cálculo')),
                ('is_salary_incidence', models.BooleanField(default=False, verbose_name='Incidencia Salarial')),
                ('calculation_trace', models.TextField(blank=True, null=True, verbose_name='Traza de Cálculo (Legacy)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll_core.payrollreceipt', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Detalle de Recibo',
                'verbose_name_plural': 'Detalles de Recibo',
            },
        ),
        migrations.DeleteModel(
            name='PayslipDetail',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
