# Generated by Django 5.0 on 2026-01-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0034_alter_payslip_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='behavior',
            field=models.CharField(choices=[('SALARY_BASE', 'Sueldo Base (Desglosable)'), ('CESTATICKET', 'Cestaticket'), ('COMPLEMENT', 'Complemento Salarial'), ('LAW_DEDUCTION', 'Deducción de Ley (IVSS, FAOV, RPE)'), ('LOAN', 'Préstamo / Anticipo'), ('DYNAMIC', 'Fórmula Dinámica'), ('FIXED', 'Monto Fijo')], default='DYNAMIC', help_text='Define cómo el motor procesa este concepto', max_length=20, verbose_name='Comportamiento'),
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='system_params',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración del Handler (rate, base_source, cap_multiplier, etc.)', verbose_name='Parámetros de Sistema'),
        ),
    ]
