# Generated by Django 5.0 on 2026-01-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0035_payrollconcept_behavior_payrollconcept_system_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='calculation_base',
            field=models.CharField(choices=[('TOTAL', 'Salario Total (Base + Complemento)'), ('BASE', 'Sueldo Base Únicamente')], default='TOTAL', help_text='Indica si el cálculo se basa en el total del contrato o solo en el sueldo base', max_length=10, verbose_name='Base de Cálculo'),
        ),
    ]
