# Generated by Django 5.0 on 2026-01-16 00:04

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0036_payrollconcept_calculation_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='LaborContract',
            name='islr_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de retención de ISLR a aplicar', max_digits=5, verbose_name='Porcentaje de Retención ISLR'),
        ),
    ]
