# Generated by Django 5.0.7 on 2026-01-19 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0037_islr_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcontract',
            name='islr_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de retención de ISLR', max_digits=5, verbose_name='Porcentaje de Retención de ISLR'),
        ),
        migrations.CreateModel(
            name='InterestRateBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Año de la tasa (ej: 2026)', verbose_name='Año')),
                ('month', models.PositiveIntegerField(help_text='Mes (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tasa mensual en porcentaje (ej: 1.5 = 1.5%)', max_digits=6, verbose_name='Tasa (%)')),
                ('source_url', models.URLField(blank=True, help_text='Enlace al comunicado oficial del BCV', verbose_name='URL Fuente BCV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('created_by', models.CharField(help_text='Usuario que registró la tasa', max_length=100, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitsSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_national_id', models.CharField(max_length=15, verbose_name='Cédula')),
                ('employee_full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('hire_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('termination_date', models.DateField(verbose_name='Fecha de Egreso')),
                ('total_garantia', models.DecimalField(decimal_places=2, help_text='Suma de todos los abonos tipo GARANTIA', max_digits=14, verbose_name='Total Garantía')),
                ('total_dias_adicionales', models.DecimalField(decimal_places=2, help_text='Suma de todos los abonos tipo DIAS_ADIC', max_digits=14, verbose_name='Total Días Adicionales')),
                ('total_intereses', models.DecimalField(decimal_places=2, help_text='Suma de todos los abonos tipo INTERES', max_digits=14, verbose_name='Total Intereses')),
                ('total_anticipos', models.DecimalField(decimal_places=2, help_text='Suma de todos los ANTICIPO (monto a restar)', max_digits=14, verbose_name='Total Anticipos')),
                ('net_garantia', models.DecimalField(decimal_places=2, help_text='= total_garantia + total_dias_adicionales + total_intereses - total_anticipos', max_digits=14, verbose_name='Neto Garantía')),
                ('years_of_service', models.DecimalField(decimal_places=2, help_text='Antigüedad en años (con decimales)', max_digits=5, verbose_name='Años de Servicio')),
                ('retroactive_days', models.DecimalField(decimal_places=2, help_text='30 días * años de servicio', max_digits=8, verbose_name='Días Retroactivos')),
                ('final_daily_salary', models.DecimalField(decimal_places=2, help_text='Salario integral diario al momento de terminar', max_digits=12, verbose_name='Salario Integral Diario Final')),
                ('retroactive_amount', models.DecimalField(decimal_places=2, help_text='= retroactive_days * final_daily_salary', max_digits=14, verbose_name='Monto Retroactivo')),
                ('chosen_method', models.CharField(choices=[('GARANTIA', 'Garantía (Art. 142 literal c)'), ('RETROACTIVO', 'Retroactivo (Art. 142 literal d)')], help_text='El que resulte mayor entre Garantía y Retroactivo', max_length=15, verbose_name='Método Elegido')),
                ('settlement_amount', models.DecimalField(decimal_places=2, help_text='Monto final a pagar al trabajador', max_digits=14, verbose_name='Monto de Liquidación')),
                ('calculation_summary', models.TextField(help_text='Explicación detallada del cálculo realizado', verbose_name='Resumen del Cálculo')),
                ('settlement_date', models.DateField(verbose_name='Fecha de Liquidación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CALCULATED', 'Calculado'), ('APPROVED', 'Aprobado'), ('PAID', 'Pagado'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=12, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('created_by', models.CharField(max_length=100, verbose_name='Creado por')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Creación')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Aprobado por')),
                ('approved_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Aprobación')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('paid_by', models.CharField(blank=True, max_length=100, verbose_name='Pagado por')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
                ('voided_by', models.CharField(blank=True, max_length=100, verbose_name='Anulado por')),
                ('void_reason', models.TextField(blank=True, verbose_name='Motivo de Anulación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='social_benefits_settlement', to='payroll_core.laborcontract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Liquidación de Prestaciones',
                'verbose_name_plural': 'Liquidaciones de Prestaciones',
                'ordering': ['-settlement_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialBenefitsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('GARANTIA', 'Garantía Trimestral (15 días)'), ('DIAS_ADIC', 'Días Adicionales por Antigüedad'), ('INTERES', 'Intereses sobre Saldo Acumulado'), ('ANTICIPO', 'Anticipo de Prestaciones'), ('LIQUIDACION', 'Liquidación Final'), ('REVERSAL', 'Reversión/Contraasiento')], max_length=15, verbose_name='Tipo de Transacción')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('period_description', models.CharField(help_text='Ej: "Q1-2026", "Año 2025", "Anticipo Marzo 2026"', max_length=50, verbose_name='Descripción del Periodo')),
                ('basis_days', models.DecimalField(decimal_places=2, help_text='Días usados en el cálculo (15, 2, etc.)', max_digits=6, verbose_name='Días Base')),
                ('daily_salary_used', models.DecimalField(decimal_places=2, help_text='Salario integral diario al momento del cálculo', max_digits=12, verbose_name='Salario Integral Diario Usado')),
                ('interest_rate_used', models.DecimalField(blank=True, decimal_places=4, help_text='Solo para transacciones tipo INTERES', max_digits=6, null=True, verbose_name='Tasa de Interés Usada (%)')),
                ('previous_balance', models.DecimalField(decimal_places=2, help_text='Saldo antes de esta transacción', max_digits=14, verbose_name='Saldo Anterior')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción (positivo=abono, negativo=cargo)', max_digits=14, verbose_name='Monto')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Saldo acumulado después de esta transacción', max_digits=14, verbose_name='Saldo Post-Movimiento')),
                ('calculation_formula', models.CharField(help_text='La fórmula usada: ej "basis_days * daily_salary_used"', max_length=200, verbose_name='Fórmula Aplicada')),
                ('calculation_trace', models.TextField(help_text='Fórmula expandida con valores: ej "15 * 125.50 = 1882.50"', verbose_name='Traza del Cálculo')),
                ('reference', models.CharField(blank=True, help_text='Número de documento, recibo, etc.', max_length=100, verbose_name='Referencia Externa')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('created_by', models.CharField(help_text='Usuario o proceso que creó el registro', max_length=100, verbose_name='Creado por')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se creó el registro', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador/Cliente usado', max_length=255, verbose_name='User Agent')),
                ('contract', models.ForeignKey(help_text='Contrato vigente al momento del movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='social_benefits_ledger', to='payroll_core.laborcontract', verbose_name='Contrato (Snapshot)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_benefits_ledger', to='payroll_core.employee', verbose_name='Empleado')),
                ('reversed_entry', models.ForeignKey(blank=True, help_text='Si es REVERSAL, apunta a la entrada original que se está revirtiendo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payroll_core.socialbenefitsledger', verbose_name='Entrada Revertida')),
            ],
            options={
                'verbose_name': 'Movimiento de Prestaciones',
                'verbose_name_plural': 'Libro de Prestaciones Sociales',
                'ordering': ['employee', '-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', '-transaction_date'], name='payroll_cor_employe_5ce0e7_idx'), models.Index(fields=['transaction_type'], name='payroll_cor_transac_52936a_idx'), models.Index(fields=['contract'], name='payroll_cor_contrac_d87055_idx')],
            },
        ),
    ]
