# Generated by Django 5.0.7 on 2026-01-21 13:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0038_alter_laborcontract_islr_retention_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='split_fixed_amount',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='split_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto fijo para usar en estrategias FIXED_BASE o FIXED_BONUS', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Fijo (Estrategia)'),
        ),
    ]
