# Generated by Django 5.0 on 2026-01-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0039_remove_company_split_fixed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='split_fixed_currency',
            field=models.ForeignKey(default='USD', help_text='Moneda del monto fijo para la estrategia (ej: USD)', on_delete=django.db.models.deletion.PROTECT, related_name='job_positions_fixed', to='payroll_core.currency', verbose_name='Moneda Monto Fijo'),
        ),
    ]
