# Generated by Django 5.0 on 2026-01-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_currency_interestratebcv_exchangerate'),
        ('payroll_core', '0040_jobposition_split_fixed_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollconcept',
            name='currency',
            field=models.ForeignKey(help_text='Moneda del valor fijo (ignorado si es porcentaje)', on_delete=django.db.models.deletion.PROTECT, to='customers.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='salary_currency',
            field=models.ForeignKey(help_text='Moneda en la que se pacta el salario (generalmente USD)', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.currency', verbose_name='Moneda del Salario'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='currency',
            field=models.ForeignKey(default='USD', help_text='Moneda del sueldo base (generalmente USD)', on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='customers.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='split_fixed_currency',
            field=models.ForeignKey(default='USD', help_text='Moneda del monto fijo para la estrategia (ej: USD)', on_delete=django.db.models.deletion.PROTECT, related_name='job_positions_fixed', to='customers.currency', verbose_name='Moneda Monto Fijo'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='currency',
            field=models.ForeignKey(help_text='Moneda del préstamo (USD o VES)', on_delete=django.db.models.deletion.PROTECT, to='customers.currency', verbose_name='Moneda'),
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='InterestRateBCV',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
