# Generated by Django 5.0 on 2026-01-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0041_alter_payrollconcept_currency_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE payroll_core_laborcontract ALTER COLUMN islr_retention_percentage SET DEFAULT 0;",
            reverse_sql="ALTER TABLE payroll_core_laborcontract ALTER COLUMN islr_retention_percentage DROP DEFAULT;"
        )
    ]
