# Generated by Django 5.0 on 2026-01-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0042_fix_islr_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='deducts_from_base_salary',
            field=models.BooleanField(default=False, help_text='Si es True, la cantidad reportada en novedades se resta de los días y valor del Sueldo Base.', verbose_name='Resta Días del Sueldo Base'),
        ),
    ]
