# Generated by Django 5.0 on 2026-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0043_payrollconcept_deducts_from_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='adds_to_complement',
            field=models.BooleanField(default=False, help_text='Si es True, el monto resultante se suma a la variable COMPLEMENTO_MENSUAL/PERIOD en el cálculo.', verbose_name='Suma al Complemento/Bono'),
        ),
    ]
