# Generated by Django 5.0 on 2026-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0044_payrollconcept_adds_to_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollconcept',
            name='formula',
            field=models.TextField(blank=True, help_text='Para DYNAMIC_FORMULA: Fórmula completa (ej: SALARIO_DIARIO * DIAS).\nPara FIXED_AMOUNT: Fórmula de AJUSTE que se SUMA al monto fijo (ej: OTRO_CONCEPTO - DESCUENTO).\nVariables especiales para ajuste: VALOR_BASE, CANTIDAD, MONTO_CALCULADO, y todos los conceptos calculados previamente.', null=True, verbose_name='Fórmula'),
        ),
    ]
