# Generated by Django 5.0.7 on 2026-01-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0045_alter_payrollconcept_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationCause',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('VACATION', 'Vacaciones'), ('ABSENCE', 'Ausencia / Falta'), ('PERMISSION', 'Permiso'), ('MATERNITY', 'Licencia Médica / Maternidad'), ('OTHER', 'Otro')], default='ABSENCE', max_length=20, verbose_name='Categoría')),
                ('is_paid', models.BooleanField(default=False, help_text='Si es True, se genera un concepto de pago positivo.', verbose_name='Remunerado')),
                ('affects_salary_days', models.BooleanField(default=True, help_text='Si es True, reduce los días de salario base en la nómina.', verbose_name='Descuenta Días Salario')),
                ('pay_concept_code', models.CharField(blank=True, help_text='Código del concepto que se usará para pagar esta variación (ej: VACACIONES).', max_length=30, null=True, verbose_name='Concepto de Pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Causa de Variación',
                'verbose_name_plural': 'Causas de Variación',
            },
        ),
        migrations.AlterField(
            model_name='payrollreceiptline',
            name='tipo_recibo',
            field=models.CharField(choices=[('salario', 'Salario Base'), ('complemento', 'Complemento'), ('cestaticket', 'Cestaticket'), ('vacaciones', 'Vacaciones')], default='salario', max_length=20, verbose_name='Tipo de Recibo'),
        ),
        migrations.CreateModel(
            name='EmployeeVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('last_processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Procesado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='payroll_core.employee', verbose_name='Empleado')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='payroll_core.variationcause', verbose_name='Causa')),
            ],
            options={
                'verbose_name': 'Variación de Empleado',
                'verbose_name_plural': 'Variaciones de Empleado',
                'ordering': ['-start_date'],
            },
        ),
    ]
