# Generated by Django 5.0.7 on 2026-01-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0045_alter_payrollconcept_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vacation_receipt_currency',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (Bs.)'), ('DUAL', 'Ambas Monedas')], default='USD', help_text='En qué moneda se muestran los montos del recibo PDF', max_length=10, verbose_name='Moneda del Recibo de Vacaciones'),
        ),
        migrations.AddField(
            model_name='company',
            name='vacation_salary_basis',
            field=models.CharField(choices=[('BASE_ONLY', 'Solo Sueldo Base'), ('BASE_PLUS_COMPLEMENT', 'Sueldo Base + Complemento (Paquete Total)')], default='BASE_PLUS_COMPLEMENT', help_text='Define qué componentes del sueldo inciden en el pago de vacaciones', max_length=25, verbose_name='Base Salarial para Vacaciones'),
        ),
    ]
