# Generated by Django 5.0.7 on 2026-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0046_variationcause_alter_payrollreceiptline_tipo_recibo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_base',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días de salario para bono vacacional el primer año (LOTTT: 15)', verbose_name='Días Base Bono Vacacional'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_max',
            field=models.PositiveSmallIntegerField(default=30, help_text='Máximo de días para bono vacacional (LOTTT: 30)', verbose_name='Máximo Días Bono Vacacional'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_per_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días adicionales de bono por cada año de servicio (LOTTT: 1)', verbose_name='Días Adicionales Bono por Año'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_base',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días hábiles de vacaciones para el primer año de servicio (LOTTT: 15)', verbose_name='Días Base Vacaciones'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_max',
            field=models.PositiveSmallIntegerField(default=30, help_text='Máximo de días de vacaciones permitidos (LOTTT: 30)', verbose_name='Máximo Días Vacaciones'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_per_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días adicionales por cada año de servicio (LOTTT: 1)', verbose_name='Días Adicionales por Año'),
        ),
    ]
