# Generated by Django 5.0.7 on 2026-01-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0047_add_vacation_policy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_year', models.PositiveSmallIntegerField(help_text='Número del año de servicio (1, 2, 3...)', verbose_name='Año de Servicio')),
                ('period_start', models.DateField(help_text='Fecha de inicio del año de servicio', verbose_name='Inicio del Período')),
                ('period_end', models.DateField(help_text='Fecha de fin del año de servicio', verbose_name='Fin del Período')),
                ('entitled_vacation_days', models.PositiveSmallIntegerField(help_text='Días de disfrute correspondientes a este año de servicio', verbose_name='Días de Vacaciones')),
                ('entitled_bonus_days', models.PositiveSmallIntegerField(help_text='Días de bono vacacional correspondientes a este año', verbose_name='Días de Bono Vacacional')),
                ('used_vacation_days', models.PositiveSmallIntegerField(default=0, help_text='Días de vacaciones ya disfrutados', verbose_name='Días Disfrutados')),
                ('bonus_paid', models.BooleanField(default=False, help_text='Indica si el bono vacacional ya fue pagado', verbose_name='Bono Pagado')),
                ('bonus_paid_date', models.DateField(blank=True, help_text='Fecha en que se pagó el bono vacacional', null=True, verbose_name='Fecha Pago Bono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Contrato asociado al periodo vacacional', on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='payroll_core.laborcontract', verbose_name='Contrato')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balances', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Saldo de Vacaciones',
                'verbose_name_plural': 'Saldos de Vacaciones',
                'ordering': ['employee', '-service_year'],
                'indexes': [models.Index(fields=['employee', 'service_year'], name='payroll_cor_employe_4f2e30_idx'), models.Index(fields=['contract', 'period_start'], name='payroll_cor_contrac_34ae89_idx')],
                'unique_together': {('employee', 'service_year')},
            },
        ),
    ]
