# Generated by Django 5.0 on 2026-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0047_create_vacation_advance_concept'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='payrollconcept',
                    name='tipo_recibo',
                    field=models.CharField(choices=[('salario', 'Salario Base'), ('complemento', 'Complemento'), ('cestaticket', 'Cestaticket')], default='salario', help_text='Determina en qué recibo se agrupa este concepto (Salario, Complemento o Cestaticket)', max_length=20, verbose_name='Tipo de Recibo'),
                ),
            ],
            database_operations=[],
        ),
    ]
