# Generated by Django 5.0.7 on 2026-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0048_add_vacation_balance_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del feriado', verbose_name='Fecha')),
                ('name', models.CharField(help_text='Descripción del feriado (ej: Navidad)', max_length=100, verbose_name='Nombre')),
                ('is_recurring', models.BooleanField(default=True, help_text='Si es True, se repite todos los años en la misma fecha (ej: 1 de Mayo)', verbose_name='Recurrente')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Día Feriado',
                'verbose_name_plural': 'Días Feriados',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='payroll_cor_date_6dbd81_idx')],
            },
        ),
    ]
