# Generated by Django 5.0 on 2026-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0048_payrollconcept_tipo_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_base',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días de bono para el primer año (Art. 192)', verbose_name='Días Base Bono Vacacional'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_max',
            field=models.PositiveSmallIntegerField(default=30, help_text='Tope máximo de días de bono vacacional', verbose_name='Máximo Días Bono Vacacional'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_base',
            field=models.PositiveSmallIntegerField(default=15, help_text='Días correspondientes al primer año (Art. 190)', verbose_name='Días Base Vacaciones'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_max',
            field=models.PositiveSmallIntegerField(default=15, help_text='Tope de días adicionales acumulables (Total máx = Base + Máx)', verbose_name='Máximo Días Adicionales'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_days_per_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días adicionales por cada año de servicio', verbose_name='Días Adicionales por Año'),
        ),
    ]
