# Generated by Django 5.0 on 2026-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0049_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconcept',
            name='tipo_recibo',
            field=models.CharField(choices=[('salario', 'Salario Base'), ('complemento', 'Complemento'), ('cestaticket', 'Cestaticket'), ('vacaciones', 'Vacaciones')], default='salario', help_text='Determina en qué tipo de recibo aparecerá este concepto.', max_length=20, verbose_name='Tipo de Recibo'),
        ),
    ]
