# Generated by Django 5.0 on 2026-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0049_payrollpolicy_vacation_bonus_days_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='accrual_mode',
            field=models.CharField(choices=[('ANNUAL', 'Anual (Al cumplir cada año)'), ('MONTHLY', 'Mensual Proporcional'), ('PROPORTIONAL', 'Proporcional a Días Trabajados')], default='ANNUAL', help_text='Cómo se acumulan los días de vacaciones', max_length=15, verbose_name='Modo de Acumulación'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='min_service_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Antigüedad mínima en meses para generar derecho a vacaciones (LOTTT: 12)', verbose_name='Meses Mínimos para Derecho'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='pay_holidays',
            field=models.BooleanField(default=True, help_text='Incluir feriados nacionales del período vacacional en el pago', verbose_name='Pagar Feriados'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='pay_rest_days',
            field=models.BooleanField(default=True, help_text='Incluir sábados/domingos del período vacacional en el pago', verbose_name='Pagar Días de Descanso'),
        ),
    ]
