# Generated by Django 5.0 on 2026-01-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0050_add_tipo_recibo_to_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('PERSONAL', 'Préstamo Personal'), ('VACATION_ADVANCE', 'Anticipo de Vacaciones')], default='PERSONAL', max_length=20, verbose_name='Tipo de Préstamo'),
        ),
        migrations.AddField(
            model_name='loan',
            name='vacation_balance',
            field=models.ForeignKey(blank=True, help_text='Asociado solo para anticipos de vacaciones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='payroll_core.vacationbalance', verbose_name='Saldo de Vacaciones'),
        ),
    ]
