# Generated by Django 5.0.7 on 2026-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0050_add_vacation_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpolicy',
            name='vacation_bonus_days_per_year',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días adicionales de bono por cada año de servicio', verbose_name='Días Adicionales Bono por Año'),
        ),
    ]
