# Generated by Django 5.0 on 2026-02-11 00:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0052_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Horario')),
                ('tolerance_minutes', models.PositiveSmallIntegerField(default=5, help_text='Minutos de gracia antes de considerar retardo', verbose_name='Tolerancia (min)')),
                ('check_in_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Hora Entrada')),
                ('lunch_start_time', models.TimeField(default=datetime.time(12, 0), verbose_name='Inicio Almuerzo')),
                ('lunch_end_time', models.TimeField(default=datetime.time(13, 0), verbose_name='Fin Almuerzo')),
                ('check_out_time', models.TimeField(default=datetime.time(17, 0), verbose_name='Hora Salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, help_text='Horario asignado para cálculo de asistencia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll_core.workschedule', verbose_name='Horario de Trabajo'),
        ),
    ]
