# Generated by Django 5.0 on 2026-02-12 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0053_workschedule_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shifts', to='payroll_core.employee', verbose_name='Empleado')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='payroll_core.workschedule', verbose_name='Horario Asignado')),
            ],
            options={
                'verbose_name': 'Turno Diario',
                'verbose_name_plural': 'Turnos Diarios',
                'indexes': [models.Index(fields=['employee', 'date'], name='payroll_cor_employe_f53628_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
