# Generated by Django 5.0 on 2026-02-22 15:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_currency_interestratebcv_exchangerate'),
        ('payroll_core', '0054_employeedailyshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('V', 'Venezolano(a)'), ('E', 'Extranjero(a)')], default='V', help_text='V=Venezolano, E=Extranjero. Requerido para IVSS/FAOV', max_length=1, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='second_last_name',
            field=models.CharField(blank=True, help_text='Requerido para archivos planos FAOV/IVSS', max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='employee',
            name='second_name',
            field=models.CharField(blank=True, help_text='Requerido para archivos planos FAOV/IVSS', max_length=50, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='cestaticket_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Monto legal del cestaticket en USD.', max_digits=10, verbose_name='Cestaticket (USD)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='faov_employee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='FAOV (Vivienda) a cargo del trabajador', max_digits=5, verbose_name='FAOV Empleado (%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='imii_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('130.00'), help_text='Ingreso Mínimo Integral Indexado en USD. Piso para LPPSS.', max_digits=10, verbose_name='IMII (USD)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='inces_employer_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Contribución patronal INCES. Actualmente 2%.', max_digits=5, verbose_name='INCES Patronal (%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='ivss_employee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Porcentaje de IVSS a cargo del trabajador', max_digits=5, verbose_name='IVSS Empleado (%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='ivss_salary_cap_multiplier',
            field=models.PositiveSmallIntegerField(default=5, help_text='El IVSS se calcula sobre un máximo de N salarios mínimos', verbose_name='Tope IVSS (x SM)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='lppss_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Contribución Especial de Pensiones (LPPSS). Actualmente 9%.', max_digits=5, verbose_name='LPPSS (%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='minimum_wage_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('130.00'), help_text='Salario mínimo mensual vigente en VES. Usado como tope IVSS.', max_digits=18, verbose_name='Salario Mínimo (Bs.)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='rpe_employee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Paro Forzoso a cargo del trabajador', max_digits=5, verbose_name='RPE Empleado (%)'),
        ),
        migrations.AddField(
            model_name='payrollpolicy',
            name='ut_value_ves',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Valor de la Unidad Tributaria vigente. Usado para cálculos ISLR.', max_digits=12, verbose_name='Valor UT (Bs.)'),
        ),
        migrations.CreateModel(
            name='INCESDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('quarter', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Trimestre (1-4)')),
                ('total_payroll_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Nómina Total Trimestre (Bs.)')),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Tasa Patronal (%)')),
                ('employer_contribution_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Contribución Patronal (Bs.)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CALCULATED', 'Calculado'), ('DECLARED', 'Declarado'), ('PAID', 'Pagado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Declaración INCES',
                'verbose_name_plural': 'Declaraciones INCES',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='ISLRRetentionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Año en que aplica esta tabla', verbose_name='Año Fiscal')),
                ('income_from_ut', models.DecimalField(decimal_places=2, help_text='Límite inferior del tramo en Unidades Tributarias', max_digits=12, verbose_name='Desde (UT)')),
                ('income_to_ut', models.DecimalField(blank=True, decimal_places=2, help_text='Límite superior del tramo en UT (null = sin límite)', max_digits=12, null=True, verbose_name='Hasta (UT)')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Porcentaje de retención para este tramo', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tarifa (%)')),
                ('subtrahend', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto a restar después de aplicar la tarifa', max_digits=12, verbose_name='Sustraendo (UT)')),
                ('ut_value', models.DecimalField(decimal_places=2, help_text='Valor de la Unidad Tributaria en Bolívares para este año fiscal', max_digits=12, verbose_name='Valor UT (Bs.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tramo ISLR',
                'verbose_name_plural': 'Tabla de Retención ISLR',
                'ordering': ['year', 'income_from_ut'],
                'unique_together': {('year', 'income_from_ut')},
            },
        ),
        migrations.CreateModel(
            name='LPPSSDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('total_employees', models.PositiveIntegerField(default=0, verbose_name='Total Empleados')),
                ('total_payroll_base_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma de salarios + bonificaciones (con piso IMII por trabajador)', max_digits=18, verbose_name='Base Total Nómina (Bs.)')),
                ('imii_usd_used', models.DecimalField(decimal_places=2, help_text='Valor del IMII en USD al momento de la declaración', max_digits=10, verbose_name='IMII USD Usado')),
                ('exchange_rate_used', models.DecimalField(decimal_places=6, help_text='Tasa de cambio para convertir IMII de USD a VES', max_digits=18, verbose_name='Tasa BCV Usada')),
                ('contribution_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Porcentaje de contribución (actualmente 9%)', max_digits=5, verbose_name='Alícuota (%)')),
                ('contribution_amount_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total a pagar = base × alícuota', max_digits=18, verbose_name='Contribución Total (Bs.)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CALCULATED', 'Calculado'), ('DECLARED', 'Declarado ante SENIAT'), ('PAID', 'Pagado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('seniat_reference', models.CharField(blank=True, max_length=50, verbose_name='Nro. de Declaración SENIAT')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Declaración LPPSS',
                'verbose_name_plural': 'Declaraciones LPPSS',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ISLRRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('taxable_income_ves', models.DecimalField(decimal_places=2, help_text='Ingreso gravable del mes en VES', max_digits=18, verbose_name='Base Imponible (Bs.)')),
                ('retention_amount_ves', models.DecimalField(decimal_places=2, help_text='ISLR retenido en el mes', max_digits=18, verbose_name='Monto Retenido (Bs.)')),
                ('accumulated_income_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ingreso acumulado del año hasta este mes', max_digits=18, verbose_name='Acumulado Anual (Bs.)')),
                ('accumulated_retention_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total retenido en el año hasta este mes', max_digits=18, verbose_name='Retención Acumulada (Bs.)')),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarifa Aplicada (%)')),
                ('ut_value_used', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor UT Usado (Bs.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='islr_retentions', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Retención ISLR',
                'verbose_name_plural': 'Retenciones ISLR',
                'ordering': ['employee', '-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='LPPSSDeclarationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_ves', models.DecimalField(decimal_places=2, help_text='Salario mensual en VES', max_digits=18, verbose_name='Salario (Bs.)')),
                ('bonuses_ves', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bonificaciones no salariales en VES', max_digits=18, verbose_name='Bonificaciones (Bs.)')),
                ('imii_floor_ves', models.DecimalField(decimal_places=2, help_text='IMII convertido a VES (mínimo por trabajador)', max_digits=18, verbose_name='Piso IMII (Bs.)')),
                ('base_applied_ves', models.DecimalField(decimal_places=2, help_text='max(salario + bonificaciones, IMII)', max_digits=18, verbose_name='Base Aplicada (Bs.)')),
                ('contribution_ves', models.DecimalField(decimal_places=2, help_text='base_applied × tasa', max_digits=18, verbose_name='Contribución (Bs.)')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll_core.lppssdeclaration', verbose_name='Declaración')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Línea LPPSS',
                'verbose_name_plural': 'Líneas LPPSS',
                'unique_together': {('declaration', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Salario mensual anterior (null si es el registro inicial)', max_digits=12, null=True, verbose_name='Monto Anterior')),
                ('new_amount', models.DecimalField(decimal_places=2, help_text='Salario mensual nuevo', max_digits=12, verbose_name='Monto Nuevo')),
                ('effective_date', models.DateField(help_text='Fecha desde la cual aplica este salario', verbose_name='Fecha de Vigencia')),
                ('reason', models.CharField(blank=True, help_text='Ej: Aumento anual, Promoción, Ajuste por inflación', max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Creado por')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_changes', to='payroll_core.laborcontract', verbose_name='Contrato')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.currency', verbose_name='Moneda')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='payroll_core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Historial Salarial',
                'verbose_name_plural': 'Historial Salarial',
                'ordering': ['employee', '-effective_date'],
                'indexes': [models.Index(fields=['employee', '-effective_date'], name='payroll_cor_employe_4e7460_idx'), models.Index(fields=['contract', '-effective_date'], name='payroll_cor_contrac_f95729_idx')],
            },
        ),
    ]
