# Generated by Django 5.0 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0055_phase1_salary_history_gov_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pants_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla de Pantalón'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla de Camisa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Talla de Calzado'),
        ),
    ]
