# Generated by Django 5.0 on 2026-02-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0056_employee_pants_size_employee_shirt_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_endowment_date',
            field=models.DateField(blank=True, help_text='Fecha de la última dotación entregada', null=True, verbose_name='Última Dotación'),
        ),
        migrations.CreateModel(
            name='EndowmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha en la que se entregó la dotación', verbose_name='Fecha de Dotación')),
                ('description', models.CharField(help_text='Breve descripción de la dotación (Ej: Uniformes Q1 2026)', max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('branch', models.ForeignKey(blank=True, help_text='Sede a la que fue dirigida la dotación (Opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endowment_events', to='payroll_core.branch', verbose_name='Sede')),
                ('employees', models.ManyToManyField(help_text='Empleados que recibieron la dotación', related_name='endowments', to='payroll_core.employee', verbose_name='Empleados')),
            ],
            options={
                'verbose_name': 'Evento de Dotación',
                'verbose_name_plural': 'Historial de Dotaciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
