# Generated by Django 5.0 on 2026-02-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0058_historicalcompany_historicaldepartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('view_menu_personnel', 'Can view Menú Personal'), ('view_menu_payroll', 'Can view Menú Nómina'), ('view_menu_catalog', 'Can view Menú Conceptos'), ('view_menu_closures', 'Can view Menú Cierres'), ('view_menu_vacations', 'Can view Menú Vacaciones'), ('view_menu_attendance', 'Can view Menú Asistencia'), ('view_menu_config', 'Can view Menú Configuración'), ('view_menu_loans', 'Can view Menú Préstamos'), ('view_menu_reports', 'Can view Menú Reportes'), ('view_menu_declarations', 'Can view Menú Ley y Gobierno')], 'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
    ]
