# Generated by Django 5.0 on 2026-03-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_core', '0061_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_approve_attendance',
            field=models.BooleanField(default=False, help_text='Si está activo, los resúmenes de asistencia por periodo se aprueban automáticamente al generar', verbose_name='Auto-Aprobar Asistencia'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='auto_approve_attendance',
            field=models.BooleanField(default=False, help_text='Si está activo, los resúmenes de asistencia por periodo se aprueban automáticamente al generar', verbose_name='Auto-Aprobar Asistencia'),
        ),
    ]
